# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
# https://docs.github.com/en/actions/reference/runners/github-hosted-runners
name: Continuous Integration (CI)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PlatformIO
        run: |
          pip install platformio

      - name: Build firmware
        run: |
          pio run

      - name: Run static analysis
        run: |
          pio check
